### ISSUE TITLE
Complete Profile Reminder Module

### ISSUE THREAD

**Issue by oh-hi** [oh-hi/maverick#45]
#### Description

We need to gently remind users to complete profile when accessing the application.

This should appear on all pages after the user logs in only if they do not have a completed profile
#### Wireframes

<img width="231" alt="screen shot 2016-10-11 at 10 28 13 pm" src="https://cloud.githubusercontent.com/assets/1194096/19296547/183a4f70-9002-11e6-9928-dabb415df18d.png">
#### Acceptance Criteria

- [ ] Must contain link to profile creation page
- [ ] Must display when accessing the internal application (after login)

**Comment by ashwoodall** [comment]
Waiting for #57 to create PR
