### ISSUE TITLE
Upload Picture needs better UX

### ISSUE THREAD

**Issue by fmaredia** [oh-hi/maverick#68]
#### Description ####

The dialog should make it clearer that the user needs to click or drag a picture there, perhaps a grey field with a material upload icon in the center? Regardless, the cursor there should be a pointer cursor instead of text cursor

#### Acceptance Criteria ####

  - [ ] User understands that they need to drag or click on the field to upload a picture and not the upload button

**Comment by yhbrandon** [comment]
done
