### ISSUE TITLE
Message delete button doesn't work

### ISSUE THREAD

**Issue by citizenkade** [oh-hi/maverick#81]
#### Description ####
Not sure if this functionality was just turned off, but the delete button for a message thread didn't work when I tested it.

#### Acceptance Criteria ####
User should be presented with a confirmation message:

"Delete this message? This cannot be undone."
[Cancel] [Delete]

If deleted, user is taken to messages list and the thread is gone.

**Comment by yhbrandon** [comment]
Yeah I left it out, will add it in now
