### ISSUE TITLE
Messages disappeared and then reappeared after refresh

### ISSUE THREAD

**Issue by citizenkade** [oh-hi/maverick#82]
#### Description ####
I sent a few messages to Brandon and then all my messages got deleted. This may have been fixed recently since Brandon said something about having updated stuff that affected Messages.

**Sequence of events that occurred:**
(1) Sent a few messages (2) Sent someone else a message (3) Came back to message thread with Brandon and tried to send another message (4) All but first message disappeared (5) Refreshed page and messages came back

#### Acceptance Criteria ####
Messages never disappear

**Comment by yhbrandon** [comment]
Yeah I need to wipe the server to retest this one
